spring:
  application:
    name: Account
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "prod"

build:
  version: 1.0

accounts:
  message: "Welcome to Bank accounts related local APIs"
  contactDetails:
    name: "Harry Potter - Developer"
    email: "potter@gmail.com"
  onCallSupports:
    - (555) 123-2345
    - (555) 345-5678
