spring:
  config:
    activate:
      on-profile:
        - "prod"
loans:
  message: "Welcome to Bank loans related prod APIs"
  contactDetails:
    name: "Rodrigo Dav - prod Lead"
    email: "rodrigo@gmail.com"
  onCallSupports:
    - (555) 111-1111
    - (555) 111-0000
