build:
  version: 1.0

accounts:
  message: "Welcome to Bank accounts related local APIs"
  contactDetails:
    name: "Harry Potter - Developer"
    email: "potter@gmail.com"
  onCallSupports:
    - (555) 123-2345
    - (555) 345-5678
